
twilio_account_sid:   'ACf39f1f192d9d9a72663cc68bc68d0af6'   
twilio_auth_token:  '45b25b476b44accdaf214980b2358c9a'
# twilio_phone_number:  '+18649900037'
twilio_phone_number:  <%= ENV.fetch("TWILIO_PHONE_NUMBER", "YOUR-TWILIO-TRIAL-PHONE-NUMBER-GOES-HERE") %>
